CREATE TABLE players
(
    player_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username  VARCHAR(255)                            NOT NULL,
    password  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_players PRIMARY KEY (player_id)
);